type: rsna
csv_path: '/home/sravar/Documents/INSPECT/RSPECT_CTPA/train.csv'
sample_frac: 1.0
dicom_dir: /home/sravar/Documents/INSPECT/RSPECT_CTPA/train
output_dir: /home/sravar/Documents/INSPECT/RSPECT_CTPA/rsna_features
target: 'pe_present_on_image'
weighted_sample: true
test_split: all

batch_size: 4

transform:
    channels: repeat 
    resize_size: 256
    crop_size: 224
    final_size: 224

