type: rsna_1d
csv_path: '/home/sravar/Documents/INSPECT/RSPECT_CTPA/train.csv'
sample_frac: 1.0
dicom_dir: /home/sravar/Documents/INSPECT/RSPECT_CTPA/train
target: 'pe_present_on_image'
contextualize_slice: False # To test 
sample_strategy: fix
num_slices: 150
feature_size: 768
weighted_sample: true
batch_size: 32
#hdf5_path: null
hdf5_path: /home/sravar/Documents/INSPECT/RSPECT_CTPA/rsna_features/features.hdf5

pretrain_args:
  model_type: resnetv2_101_ct
  input_size: 256
  channel_type: window
