type: 2d
csv_path: '/home/users/steven/INSPECT/DATA_RAW/LABELS/series_metadata_20250611.tsv'
split_path: '/home/users/steven/INSPECT/DATA_RAW/LABELS/splits_20250611.tsv'
metadata_path: '/home/users/steven/INSPECT/DATA_RAW/LABELS/series_metadata_20250611.tsv'
sample_frac: 1.0
dicom_dir: /data/scratch/INSPECT/INSPECT_CTPA
output_dir: /data/processed/INSPECT/CNN_embeddings

batch_size: 256
weighted_sample: false

transform:
    channels: window
    resize_size: 256
    crop_size: 224
    final_size: 224
