n_gpus: 1
get_features: true
stage: extract
#output_dir: /home/mschuang/radfusion3.0/outputs
test_split: all

exp:
  base_dir: /data/processed/INSPECT/CNN_embeddings
  name: all # test

trainer:
  weights_summary: top
  seed: 6
  val_check_interval: 1.0
  limit_val_batches: 1.0
  resume_from_checkpoint: null
  precision: "bf16-mixed"  # use BF16 mixed precision
  max_steps: 100_000
  gradient_clip_val: 0
  num_workers: 32

defaults:
  - dataset: stanford
  - model: resnetv2_ct # dinov2
