python run_classify.py model=model_1d dataset=stanford_featurized \
	dataset.target=1_month_mortality \
	dataset.pretrain_args.model_type=resnetv2_101_ct\
	dataset.pretrain_args.channel_type=window\
	dataset.feature_size=768 \
	dataset.num_slices=250 \
	model.aggregation=attention \
	model.seq_encoder.rnn_type=GRU \
	model.seq_encoder.bidirectional=true\
	model.seq_encoder.num_layers=1\
	model.seq_encoder.dropout_prob=0.5\
	dataset.weighted_sample=false \
	trainer.max_epochs=1\
	lr=0.001 \
    exp.base_dir="/data/processed/INSPECT/CNN_embeddings" \
    output_dir="/data/processed/INSPECT/CNN_embeddings/wandb" \
    dataset.csv_path="/home/users/steven/INSPECT/DATA_RAW/LABELS/series_metadata_20250611.tsv" \
    dataset.label_csv="/home/users/steven/INSPECT/DATA_RAW/LABELS/labels_20250611.tsv" \
    dataset.split_csv="/home/users/steven/INSPECT/DATA_RAW/LABELS/splits_20250611.tsv"